lab50:
  window:
    - editor
    - readme
    - terminal


check50:
  files:
    - !exclude "*"
    - !require "src/app.js"
  dependencies:
    - "git+https://github.com/cs50/check50_js.git#egg=check50_js"
